"""Add ParameterPreset model

Revision ID: 337111738a35
Revises: ee71111c2f79
Create Date: 2025-07-17 15:25:20.802852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '337111738a35'
down_revision: Union[str, None] = 'ee71111c2f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parameter_presets', 'column_mapping')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parameter_presets', sa.Column('column_mapping', sqlite.JSON(), nullable=False))
    # ### end Alembic commands ###
