"""Add missing columns to batch_calculation_results

Revision ID: ee71111c2f79
Revises: 3a8e4756a9c4
Create Date: 2025-07-17 15:12:20.701046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee71111c2f79'
down_revision: Union[str, None] = '3a8e4756a9c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with default values to handle existing records
    op.add_column('batch_calculation_results', sa.Column('total_bonus_pool', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('batch_calculation_results', sa.Column('average_bonus', sa.Float(), nullable=True))
    op.add_column('batch_calculation_results', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batch_calculation_results', 'created_at')
    op.drop_column('batch_calculation_results', 'average_bonus')
    op.drop_column('batch_calculation_results', 'total_bonus_pool')
    # ### end Alembic commands ###
